# Creates a local MySQL server with a PlanetScale API-compliant proxy.
# Adminer is included for easy database management.

version: "3.8"

services:
  mysql:
    image: mysql:8.0
    restart: always
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_DATABASE: restauwants
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - 3306:3306
    volumes:
      - mysql:/var/lib/mysql

  planetscale-proxy:
    # Source: https://github.com/mattrobenolt/ps-http-sim/tree/main
    image: ghcr.io/mattrobenolt/ps-http-sim:latest
    command:
      [
        "-listen-port=3900",
        "-mysql-dbname=restauwants",
        "-mysql-addr=mysql",
      ]
    depends_on:
      - mysql
    ports:
      - 3900:3900

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
    environment:
      ADMINER_DEFAULT_SERVER: mysql

volumes:
  mysql:
